// Mocks generated by Mockito 5.4.6 from annotations
// in mplatform_mobile/test/features/records/presentation/providers/records_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mplatform_mobile/features/records/data/repositories/records_repository.dart'
    as _i4;
import 'package:mplatform_mobile/features/records/domain/models/classification_node_model.dart'
    as _i8;
import 'package:mplatform_mobile/features/records/domain/models/domain_model.dart'
    as _i6;
import 'package:mplatform_mobile/features/records/domain/models/field_definition.dart'
    as _i7;
import 'package:mplatform_mobile/features/records/domain/models/record_item.dart'
    as _i3;
import 'package:mplatform_mobile/features/records/domain/models/records_page_response.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecordsPageResponse_0 extends _i1.SmartFake
    implements _i2.RecordsPageResponse {
  _FakeRecordsPageResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordItem_1 extends _i1.SmartFake implements _i3.RecordItem {
  _FakeRecordItem_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecordsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordsRepository extends _i1.Mock implements _i4.RecordsRepository {
  MockRecordsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.DomainModel>> getDomains() =>
      (super.noSuchMethod(
            Invocation.method(#getDomains, []),
            returnValue: _i5.Future<List<_i6.DomainModel>>.value(
              <_i6.DomainModel>[],
            ),
          )
          as _i5.Future<List<_i6.DomainModel>>);

  @override
  _i5.Future<List<_i7.FieldDefinition>> getFieldDefinitions(String? domainId) =>
      (super.noSuchMethod(
            Invocation.method(#getFieldDefinitions, [domainId]),
            returnValue: _i5.Future<List<_i7.FieldDefinition>>.value(
              <_i7.FieldDefinition>[],
            ),
          )
          as _i5.Future<List<_i7.FieldDefinition>>);

  @override
  _i5.Future<List<_i7.FieldDefinition>> getEffectiveNodeFields(
    String? nodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEffectiveNodeFields, [nodeId]),
            returnValue: _i5.Future<List<_i7.FieldDefinition>>.value(
              <_i7.FieldDefinition>[],
            ),
          )
          as _i5.Future<List<_i7.FieldDefinition>>);

  @override
  _i5.Future<List<_i8.ClassificationNodeModel>> getClassificationTree(
    String? domainId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getClassificationTree, [domainId]),
            returnValue: _i5.Future<List<_i8.ClassificationNodeModel>>.value(
              <_i8.ClassificationNodeModel>[],
            ),
          )
          as _i5.Future<List<_i8.ClassificationNodeModel>>);

  @override
  _i5.Future<_i2.RecordsPageResponse> getRecords({
    required String? domainId,
    String? nodeId,
    int? page = 0,
    int? size = 20,
    String? searchQuery,
    List<String>? searchFields,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, [], {
              #domainId: domainId,
              #nodeId: nodeId,
              #page: page,
              #size: size,
              #searchQuery: searchQuery,
              #searchFields: searchFields,
              #filters: filters,
            }),
            returnValue: _i5.Future<_i2.RecordsPageResponse>.value(
              _FakeRecordsPageResponse_0(
                this,
                Invocation.method(#getRecords, [], {
                  #domainId: domainId,
                  #nodeId: nodeId,
                  #page: page,
                  #size: size,
                  #searchQuery: searchQuery,
                  #searchFields: searchFields,
                  #filters: filters,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.RecordsPageResponse>);

  @override
  _i5.Future<_i3.RecordItem> getRecordDetail(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordDetail, [recordId]),
            returnValue: _i5.Future<_i3.RecordItem>.value(
              _FakeRecordItem_1(
                this,
                Invocation.method(#getRecordDetail, [recordId]),
              ),
            ),
          )
          as _i5.Future<_i3.RecordItem>);

  @override
  _i5.Future<Map<String, String>> decryptRecordFields({
    required String? recordId,
    required List<String>? fieldKeys,
    required String? accessReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptRecordFields, [], {
              #recordId: recordId,
              #fieldKeys: fieldKeys,
              #accessReason: accessReason,
            }),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRecordHistory(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordHistory, [recordId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, String>> decryptHistoryFields({
    required String? historyId,
    required List<String>? fieldKeys,
    required String? accessReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptHistoryFields, [], {
              #historyId: historyId,
              #fieldKeys: fieldKeys,
              #accessReason: accessReason,
            }),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);
}
