// Mocks generated by Mockito 5.4.6 from annotations
// in mplatform_mobile/test/features/approvals/presentation/providers/approvals_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mplatform_mobile/features/approvals/data/repositories/approvals_repository.dart'
    as _i2;
import 'package:mplatform_mobile/features/approvals/domain/models/approval_item.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApprovalsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprovalsRepository extends _i1.Mock
    implements _i2.ApprovalsRepository {
  MockApprovalsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ApprovalItem>> getPendingApprovals() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingApprovals, []),
            returnValue: _i3.Future<List<_i4.ApprovalItem>>.value(
              <_i4.ApprovalItem>[],
            ),
          )
          as _i3.Future<List<_i4.ApprovalItem>>);

  @override
  _i3.Future<_i4.ApprovalItem?> getApprovalDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getApprovalDetail, [id]),
            returnValue: _i3.Future<_i4.ApprovalItem?>.value(),
          )
          as _i3.Future<_i4.ApprovalItem?>);

  @override
  _i3.Future<List<_i4.ApprovalItem>> getMySubmittedApprovals() =>
      (super.noSuchMethod(
            Invocation.method(#getMySubmittedApprovals, []),
            returnValue: _i3.Future<List<_i4.ApprovalItem>>.value(
              <_i4.ApprovalItem>[],
            ),
          )
          as _i3.Future<List<_i4.ApprovalItem>>);

  @override
  _i3.Future<bool> approveRequest(String? approvalId, {String? comment}) =>
      (super.noSuchMethod(
            Invocation.method(
              #approveRequest,
              [approvalId],
              {#comment: comment},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> rejectRequest(String? approvalId, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#rejectRequest, [approvalId], {#reason: reason}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> cancelApprovalRequest(String? requestId, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(
              #cancelApprovalRequest,
              [requestId],
              {#reason: reason},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
