// Mocks generated by Mockito 5.4.6 from annotations
// in mplatform_mobile/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:mplatform_mobile/features/approvals/data/repositories/approvals_repository.dart'
    as _i14;
import 'package:mplatform_mobile/features/approvals/domain/models/approval_item.dart'
    as _i15;
import 'package:mplatform_mobile/features/auth/data/repositories/auth_repository.dart'
    as _i7;
import 'package:mplatform_mobile/features/auth/domain/models/auth_response.dart'
    as _i2;
import 'package:mplatform_mobile/features/auth/domain/models/user_model.dart'
    as _i9;
import 'package:mplatform_mobile/features/chat/data/repositories/chat_repository.dart'
    as _i16;
import 'package:mplatform_mobile/features/chat/data/services/chat_websocket_service.dart'
    as _i18;
import 'package:mplatform_mobile/features/chat/domain/models/chat_message_model.dart'
    as _i5;
import 'package:mplatform_mobile/features/chat/domain/models/chat_room_model.dart'
    as _i6;
import 'package:mplatform_mobile/features/records/data/repositories/records_repository.dart'
    as _i10;
import 'package:mplatform_mobile/features/records/domain/models/classification_node_model.dart'
    as _i13;
import 'package:mplatform_mobile/features/records/domain/models/domain_model.dart'
    as _i11;
import 'package:mplatform_mobile/features/records/domain/models/field_definition.dart'
    as _i12;
import 'package:mplatform_mobile/features/records/domain/models/record_item.dart'
    as _i4;
import 'package:mplatform_mobile/features/records/domain/models/records_page_response.dart'
    as _i3;
import 'package:stomp_dart_client/stomp_dart_client.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordsPageResponse_1 extends _i1.SmartFake
    implements _i3.RecordsPageResponse {
  _FakeRecordsPageResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordItem_2 extends _i1.SmartFake implements _i4.RecordItem {
  _FakeRecordItem_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatMessageModel_3 extends _i1.SmartFake
    implements _i5.ChatMessageModel {
  _FakeChatMessageModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatRoomModel_4 extends _i1.SmartFake implements _i6.ChatRoomModel {
  _FakeChatRoomModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.AuthResponse> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i8.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.AuthResponse>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i9.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i8.Future<_i9.UserModel?>.value(),
          )
          as _i8.Future<_i9.UserModel?>);

  @override
  _i8.Future<List<_i9.UserModel>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i8.Future<List<_i9.UserModel>>.value(
              <_i9.UserModel>[],
            ),
          )
          as _i8.Future<List<_i9.UserModel>>);
}

/// A class which mocks [RecordsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordsRepository extends _i1.Mock implements _i10.RecordsRepository {
  MockRecordsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i11.DomainModel>> getDomains() =>
      (super.noSuchMethod(
            Invocation.method(#getDomains, []),
            returnValue: _i8.Future<List<_i11.DomainModel>>.value(
              <_i11.DomainModel>[],
            ),
          )
          as _i8.Future<List<_i11.DomainModel>>);

  @override
  _i8.Future<List<_i12.FieldDefinition>> getFieldDefinitions(
    String? domainId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFieldDefinitions, [domainId]),
            returnValue: _i8.Future<List<_i12.FieldDefinition>>.value(
              <_i12.FieldDefinition>[],
            ),
          )
          as _i8.Future<List<_i12.FieldDefinition>>);

  @override
  _i8.Future<List<_i13.ClassificationNodeModel>> getClassificationTree(
    String? domainId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getClassificationTree, [domainId]),
            returnValue: _i8.Future<List<_i13.ClassificationNodeModel>>.value(
              <_i13.ClassificationNodeModel>[],
            ),
          )
          as _i8.Future<List<_i13.ClassificationNodeModel>>);

  @override
  _i8.Future<_i3.RecordsPageResponse> getRecords({
    required String? domainId,
    String? nodeId,
    int? page = 0,
    int? size = 20,
    String? searchQuery,
    List<String>? searchFields,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, [], {
              #domainId: domainId,
              #nodeId: nodeId,
              #page: page,
              #size: size,
              #searchQuery: searchQuery,
              #searchFields: searchFields,
              #filters: filters,
            }),
            returnValue: _i8.Future<_i3.RecordsPageResponse>.value(
              _FakeRecordsPageResponse_1(
                this,
                Invocation.method(#getRecords, [], {
                  #domainId: domainId,
                  #nodeId: nodeId,
                  #page: page,
                  #size: size,
                  #searchQuery: searchQuery,
                  #searchFields: searchFields,
                  #filters: filters,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.RecordsPageResponse>);

  @override
  _i8.Future<_i4.RecordItem> getRecordDetail(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordDetail, [recordId]),
            returnValue: _i8.Future<_i4.RecordItem>.value(
              _FakeRecordItem_2(
                this,
                Invocation.method(#getRecordDetail, [recordId]),
              ),
            ),
          )
          as _i8.Future<_i4.RecordItem>);

  @override
  _i8.Future<Map<String, String>> decryptRecordFields({
    required String? recordId,
    required List<String>? fieldKeys,
    required String? accessReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptRecordFields, [], {
              #recordId: recordId,
              #fieldKeys: fieldKeys,
              #accessReason: accessReason,
            }),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getRecordHistory(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordHistory, [recordId]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, String>> decryptHistoryFields({
    required String? historyId,
    required List<String>? fieldKeys,
    required String? accessReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptHistoryFields, [], {
              #historyId: historyId,
              #fieldKeys: fieldKeys,
              #accessReason: accessReason,
            }),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);
}

/// A class which mocks [ApprovalsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprovalsRepository extends _i1.Mock
    implements _i14.ApprovalsRepository {
  MockApprovalsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i15.ApprovalItem>> getPendingApprovals() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingApprovals, []),
            returnValue: _i8.Future<List<_i15.ApprovalItem>>.value(
              <_i15.ApprovalItem>[],
            ),
          )
          as _i8.Future<List<_i15.ApprovalItem>>);

  @override
  _i8.Future<_i15.ApprovalItem?> getApprovalDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getApprovalDetail, [id]),
            returnValue: _i8.Future<_i15.ApprovalItem?>.value(),
          )
          as _i8.Future<_i15.ApprovalItem?>);

  @override
  _i8.Future<List<_i15.ApprovalItem>> getMySubmittedApprovals() =>
      (super.noSuchMethod(
            Invocation.method(#getMySubmittedApprovals, []),
            returnValue: _i8.Future<List<_i15.ApprovalItem>>.value(
              <_i15.ApprovalItem>[],
            ),
          )
          as _i8.Future<List<_i15.ApprovalItem>>);

  @override
  _i8.Future<bool> approveRequest(String? approvalId, {String? comment}) =>
      (super.noSuchMethod(
            Invocation.method(
              #approveRequest,
              [approvalId],
              {#comment: comment},
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> rejectRequest(String? approvalId, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#rejectRequest, [approvalId], {#reason: reason}),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i16.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i6.ChatRoomModel>> getChatRooms() =>
      (super.noSuchMethod(
            Invocation.method(#getChatRooms, []),
            returnValue: _i8.Future<List<_i6.ChatRoomModel>>.value(
              <_i6.ChatRoomModel>[],
            ),
          )
          as _i8.Future<List<_i6.ChatRoomModel>>);

  @override
  _i8.Future<List<String>> getOnlineUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineUsers, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<dynamic>> getRoomMembers(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomMembers, [roomId]),
            returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<List<_i5.ChatMessageModel>> getMessages(
    String? roomId, {
    int? page = 0,
    int? size = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [roomId],
              {#page: page, #size: size},
            ),
            returnValue: _i8.Future<List<_i5.ChatMessageModel>>.value(
              <_i5.ChatMessageModel>[],
            ),
          )
          as _i8.Future<List<_i5.ChatMessageModel>>);

  @override
  _i8.Future<_i5.ChatMessageModel> sendMessage(
    String? roomId, {
    required String? content,
    String? attachmentUrl,
    String? messageType = 'TEXT',
    String? fileUrl,
    String? fileName,
    int? fileSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [roomId],
              {
                #content: content,
                #attachmentUrl: attachmentUrl,
                #messageType: messageType,
                #fileUrl: fileUrl,
                #fileName: fileName,
                #fileSize: fileSize,
              },
            ),
            returnValue: _i8.Future<_i5.ChatMessageModel>.value(
              _FakeChatMessageModel_3(
                this,
                Invocation.method(
                  #sendMessage,
                  [roomId],
                  {
                    #content: content,
                    #attachmentUrl: attachmentUrl,
                    #messageType: messageType,
                    #fileUrl: fileUrl,
                    #fileName: fileName,
                    #fileSize: fileSize,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i5.ChatMessageModel>);

  @override
  _i8.Future<_i6.ChatRoomModel> createRoom({
    required String? title,
    required List<String>? participants,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRoom, [], {
              #title: title,
              #participants: participants,
            }),
            returnValue: _i8.Future<_i6.ChatRoomModel>.value(
              _FakeChatRoomModel_4(
                this,
                Invocation.method(#createRoom, [], {
                  #title: title,
                  #participants: participants,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.ChatRoomModel>);

  @override
  _i8.Future<bool> markRoomAsRead(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#markRoomAsRead, [roomId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<int> fetchTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTotalUnreadCount, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<Map<String, dynamic>> uploadFile(
    List<int>? fileBytes,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [fileBytes, fileName]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<String> translateMessage(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#translateMessage, [text]),
            returnValue: _i8.Future<String>.value(
              _i17.dummyValue<String>(
                this,
                Invocation.method(#translateMessage, [text]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<bool> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> leaveRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveRoom, [roomId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoom, [roomId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> delegateCreator(String? roomId, String? newCreatorId) =>
      (super.noSuchMethod(
            Invocation.method(#delegateCreator, [roomId, newCreatorId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> inviteMembers(
    String? roomId,
    List<String>? userIds, {
    int? pastMessageHours = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #inviteMembers,
              [roomId, userIds],
              {#pastMessageHours: pastMessageHours},
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> kickMember(String? roomId, String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#kickMember, [roomId, targetUserId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [ChatWebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatWebSocketService extends _i1.Mock
    implements _i18.ChatWebSocketService {
  MockChatWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i5.ChatMessageModel> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i8.Stream<_i5.ChatMessageModel>.empty(),
          )
          as _i8.Stream<_i5.ChatMessageModel>);

  @override
  _i8.Stream<String> get roomReadStream =>
      (super.noSuchMethod(
            Invocation.getter(#roomReadStream),
            returnValue: _i8.Stream<String>.empty(),
          )
          as _i8.Stream<String>);

  @override
  _i8.Stream<Map<String, dynamic>> get presenceStream =>
      (super.noSuchMethod(
            Invocation.getter(#presenceStream),
            returnValue: _i8.Stream<Map<String, dynamic>>.empty(),
          )
          as _i8.Stream<Map<String, dynamic>>);

  @override
  _i8.Stream<Map<String, dynamic>> get notificationStream =>
      (super.noSuchMethod(
            Invocation.getter(#notificationStream),
            returnValue: _i8.Stream<Map<String, dynamic>>.empty(),
          )
          as _i8.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i8.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onConnect(_i19.StompFrame? frame) => super.noSuchMethod(
    Invocation.method(#onConnect, [frame]),
    returnValueForMissingStub: null,
  );

  @override
  void subscribeToRoom(String? roomId) => super.noSuchMethod(
    Invocation.method(#subscribeToRoom, [roomId]),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribeFromRoom() => super.noSuchMethod(
    Invocation.method(#unsubscribeFromRoom, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
