server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    url: ${MARIADB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    initialization-mode: always

  data:
    mongodb:
      uri: ${MONGO_URI}
    rest.base-path: /api

  jpa:
    open-in-view: false
    hibernate:
      cache:
        use_secound_level_cache: true
        region:
          factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
      ddl-auto: update
      naming:
        physical-strategy: com.favorsoft.mplatform.config.CustomPhysicalNamingStrategy
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      connection:
        characterEncoding: utf-8
        CharSet: utf-8
        useUnicode: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.security: debug

javers:
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000

mybatis:
  mapper-locations: /mybatis/query/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}

upload:
  path: ${UPLOAD_PATH}

management:
  endpoint:
    shutdown:
      enabled: true
    