apiVersion: v1
kind: ConfigMap
metadata:
  name: mdm-config
  namespace: mdm-system
data:
  # DB
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "domain_system"
  DB_USERNAME: "postgres"
  DDL_AUTO: "update"
  TZ: "Asia/Seoul"
  
  # External Services
  OPENSEARCH_URIS: "http://opensearch:9200"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Auth / Keycloak
  JWK_SET_URI: "http://keycloak:8080/auth/realms/mplatform/protocol/openid-connect/certs"
  KEYCLOAK_SERVER_URL: "http://keycloak:8080/auth"
  KEYCLOAK_REALM: "mplatform"
  KEYCLOAK_ADMIN_CLIENT_ID: "admin-cli"
  KEYCLOAK_TOKEN_URI: "http://keycloak:8080/auth/realms/mplatform/protocol/openid-connect/token"
  KEYCLOAK_CLIENT_ID: "mdm-frontend"
  
  # Backend Settings
  JWT_ACCESS_EXPIRATION_SEC: "1800"
  JWT_REFRESH_EXPIRATION_SEC: "172800"
  JWT_EXPIRATION: "86400000"
  STORAGE_TYPE: "minio"
  MINIO_URL: "http://minio:9000"
  MINIO_BUCKET_NAME: "domain-system"
  SPRING_PROFILES_ACTIVE: "prod"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080,http://localhost:9090,http://127.0.0.1:9090"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "domain-system-group"
  DQ_ENGINE_CUSTOM_SPEL_ENABLED: "true"
  FILE_UPLOAD_DIR: "/app/uploads"
  CHAT_RETENTION_DAYS: "7"
  
  # Frontend Settings
  OAUTH2_ISSUER_URI: "http://mplatform.local/auth/realms/mplatform"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL: "http://mplatform.local/auth/realms/mplatform"
  KEYCLOAK_REDIRECT_URI: "http://mplatform.local/auth/keycloak/callback"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_REDIRECT_URI: "http://mplatform.local/auth/keycloak/callback"
  KEYCLOAK_LOGOUT_REDIRECT_URI: "http://mplatform.local/login"
  NUXT_OIDC_PROVIDERS_KEYCLOAK_LOGOUT_REDIRECT_URI: "http://mplatform.local/login"
  NUXT_PUBLIC_API_BASE: "http://mplatform.local/api"
  NUXT_PUBLIC_ACCESS_TOKEN_EXPIRATION_SEC: "1800"
  NUXT_PUBLIC_REFRESH_TOKEN_EXPIRATION_SEC: "172800"
  NUXT_OIDC_SESSION_COOKIE_SECURE: "false"
  NUXT_OIDC_COOKIE_SECURE: "false"
  NUXT_SESSION_COOKIE_SECURE: "false"
  NUXT_OIDC_SESSION_AUTOMATIC_REFRESH: "true"
  NUXT_OIDC_SESSION_EXPIRATION_CHECK: "true"
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "3000"


---
apiVersion: v1
kind: Secret
metadata:
  name: mdm-secrets
  namespace: mdm-system
type: Opaque
stringData:
  DB_PASSWORD: "password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  RABBITMQ_PASSWORD: "guest"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KEYCLOAK_ADMIN_CLIENT_SECRET: "Yr0F7nHXe5dasmunoNXRL4S81HF7tUIM"
  JWT_SECRET: "YOUR_SUPER_SECRET_KEY_FOR_JWT_AUTHENTICATION_OVER_256_BITS"
  ENCRYPTION_SECRET_KEY: "your_encryption_secret_key_which_must_be_at_least_256_bits_long"
  NUXT_OIDC_SESSION_SECRET: "NlhsR8Ak3KmuSmETkuWo97F2NOlv72UcvXWRAtgvsOrT1Y8n"
  NUXT_OIDC_TOKEN_KEY: "data:;base64,4bRR/K5TVe98TP1itI2lvT2HZYG4lGBT02vmqtHnhLE="
  NUXT_OIDC_AUTH_SESSION_SECRET: "CNwSsFJo3EZRs-6qwK9ZT7p4bcDza3Ov1Sd_AA-QB33iUjQY"
