apiVersion: v1
kind: ConfigMap
metadata:
  name: mdm-config
  namespace: mdm-system
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "domain_system"
  DB_USERNAME: "postgres"
  OPENSEARCH_URIS: "http://opensearch:9200"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  OAUTH2_ISSUER_URI: "http://keycloak:8080/realms/mplatform"
  STORAGE_TYPE: "minio"
  MINIO_URL: "http://minio:9000"
  MINIO_BUCKET_NAME: "domain-system"
  SPRING_PROFILES_ACTIVE: "prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: mdm-secrets
  namespace: mdm-system
type: Opaque
stringData:
  DB_PASSWORD: "password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  RABBITMQ_PASSWORD: "guest"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
