apiVersion: v1
kind: Secret
metadata:
  name: mail-tls-secret
  namespace: mdm-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGzCCAgOgAwIBAgIUG+xNvkqnKmW14cSrcSWvl15rxZIwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwSbWFpbC5tcGxhdGZvcm0uY29tMB4XDTI2MDgxODAwNTIw
    N1oXDTM2MDgxNTAwNTIwN1owHTEbMBkGA1UEAwwSbWFpbC5tcGxhdGZvcm0uY29t
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3CdhKy1HeYZTkIX8JRqR
    CgMxTwi5/+My43vUD5zh8tYOOSrywPJNAukB+uMUVDPy8vzYqfzNNIXU4ePJtbUV
    Ww1TVUrgjzOVWgGHEGnHVxNQH1jTfyF3UkPK3R9Wl2LFOE08FBQ/yXEjbAuoR9xw
    TLNrf59rkx7/BxTJIdI8mpJ3qMhK8SmD5o4pCxsKYg8Gc1N/THhoWw6YPuROZDgL
    K6oLwZQlayZCIVMTTB44j5bYCpNOUaDNTrQhsbUsJnDvuFKlAl05s9j9RZmIQyhZ
    UUa268vPTZteUOf08TkxDmRQGj7b/1e95suSnUVo+C3nfP0X4nFmaLV8CuL0YCZt
    rwIDAQABo1MwUTAdBgNVHQ4EFgQUiXnJnANTfTUzZxsrVpaRizBr0wkwHwYDVR0j
    BBgwFoAUiXnJnANTfTUzZxsrVpaRizBr0wkwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAnrfqz3o40qODxaH7Nvj6OY1HgPv0WKtaQC6x6roHN77r
    AQwQCKtbgiXFvMY7xd/ZD8EcYs0hkjOsEXSgQaOVjxNc/k2MaATD1G3KdIBycRHU
    iYIEjdgtlk+b3RiO313qKoN1VtMjj3hE3uR/nQsFDqnKMTN3nXXGQkfX8XN2o4J5
    vKl39+ZIbOwBhltr3bOoHVYrxjjUxGhSPOBxriRC1W3ZmiPNLoRlsyb95PZT/0WA
    Zvv1bDaAAI5uuT45dSR7TZ6eAkjPsp0to3fk60TpCZOyVm2sACtmhjUqIOENSX/t
    YvP53FNOfaCDTvMPWeKUSb+2R6p9coTdUj+AhZBsOA==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDcJ2ErLUd5hlOQ
    hfwlGpEKAzFPCLn/4zLje9QPnOHy1g45KvLA8k0C6QH64xRUM/Ly/Nip/M00hdTh
    48m1tRVbDVNVSuCPM5VaAYcQacdXE1AfWNN/IXdSQ8rdH1aXYsU4TTwUFD/JcSNs
    C6hH3HBMs2t/n2uTHv8HFMkh0jyakneoyErxKYPmjikLGwpiDwZzU39MeGhbDpg+
    5E5kOAsrqgvBlCVrJkIhUxNMHjiPltgKk05RoM1OtCGxtSwmcO+4UqUCXTmz2P1F
    mYhDKFlRRrbry89Nm15Q5/TxOTEOZFAaPtv/V73my5KdRWj4Led8/RficWZotXwK
    4vRgJm2vAgMBAAECggEAXFhgV94cVwtTThIFnAKyyAJi0oYUjxNcKzOr1gi2dkf3
    m186iFiamRfn7rcFtfQ8elQ5BcS2xstEaqRD3eZhWNoUFHjeDPNUOHbfkrDsHshJ
    GX0G6hK9nFI3a91TUxjpJR6wjrOXtgWxGAcjxVDgAixYcSYL16Bu1SeQ3pDzPtpe
    EIAkGvOxwDSAnIPnQQuPk6wvGRSeKVh/jHoAIBi919zlEqsPAivYVzGrhRsQrRkE
    Qr25UNqqvdM0yKLvstEak5vYWQgwOZVekeN62Y1bAzlK44K3o1h49VaL/Wb1zlal
    0c0tAbCKpFLn1VMoCkGUujAhXkdwJMleT+QH8w2fUQKBgQDuxbCl4JOnVTNiHZp6
    /TWWoUl+h+1Nk3tvkg2UlII2pew8d5+PuB23dzRUuZMT69YtpcaaNEYdlAefnFlE
    iDEpNNmDIn8FjzGBa6fJjapo27YTqCEYry6dlShxzGhYtyWWIZICYEBD1PZmRpM1
    3fbEaVTX9E/qTlpsMpaZXt3ZEwKBgQDsCcsI4mW6aRqM9RisGtOCHgf3OFGZCdrb
    TEqMfvaIqEirLd4lC07Fh0ELgUEOGhkyLAMkzxLfVHquQ2cKE525sWX8fGyiuL65
    72sd7cGK6RyClrNYOhwanoLzP3WSUUfjceoU1ztFWlzMdIrs7dXsmdePra5Sn4KS
    5aFqyfPodQJ/RQTgCxLfm38FW1czUFnhI6l7lRe1gLcg9x9AzbIf8awEnXX2qZSP
    Anlypwr9eMSzJH7G6cwyeFpR2dFX/HdhvoeIWF+gV/sMVFzKI3jPyX+5IfV3m6sH
    zoVPK5Xqk7pdIwiRLB6mdPUaRHYiF3AR5LSN0d7NOu1rNdtprOu/NQKBgQCXxJg7
    By830/rRZYrOppUW1e5zRFAbId4KIZzRh5VHO0U2Y9CxavrkQVpOZnaI9bj7rJb8
    5PSSisQzJn2rWf+RdYJI/UvwuO9RqKLsZIKMqeS+Bt4cPYjyiLdUZppXUVHy6b0E
    V3vx1O9UOx9UxnxFnImhBaDP2WZgw6uteVsOPQKBgQCxwPERBrINASk2y+8C4an+
    faizEp3zmPriqWxQ/V412OSr50iBe6mjlS7H/SUF9HhAtN1Wi7k1V8RM532RfnM3
    O+e167a9wdqWUiPRcmUq8Q64kkJFC/y1XyaqTP7Gqb6sFOGJcSWrD4hTO9zo+sud
    1+H3gnrEv4kc0cizghteJw==
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: mplatform-tls-secret
  namespace: mdm-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGzCCAgOgAwIBAgIUG+xNvkqnKmW14cSrcSWvl15rxZIwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwSbWFpbC5tcGxhdGZvcm0uY29tMB4XDTI2MDgxODAwNTIw
    N1oXDTM2MDgxNTAwNTIwN1owHTEbMBkGA1UEAwwSbWFpbC5tcGxhdGZvcm0uY29t
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3CdhKy1HeYZTkIX8JRqR
    CgMxTwi5/+My43vUD5zh8tYOOSrywPJNAukB+uMUVDPy8vzYqfzNNIXU4ePJtbUV
    Ww1TVUrgjzOVWgGHEGnHVxNQH1jTfyF3UkPK3R9Wl2LFOE08FBQ/yXEjbAuoR9xw
    TLNrf59rkx7/BxTJIdI8mpJ3qMhK8SmD5o4pCxsKYg8Gc1N/THhoWw6YPuROZDgL
    K6oLwZQlayZCIVMTTB44j5bYCpNOUaDNTrQhsbUsJnDvuFKlAl05s9j9RZmIQyhZ
    UUa268vPTZteUOf08TkxDmRQGj7b/1e95suSnUVo+C3nfP0X4nFmaLV8CuL0YCZt
    rwIDAQABo1MwUTAdBgNVHQ4EFgQUiXnJnANTfTUzZxsrVpaRizBr0wkwHwYDVR0j
    BBgwFoAUiXnJnANTfTUzZxsrVpaRizBr0wkwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAnrfqz3o40qODxaH7Nvj6OY1HgPv0WKtaQC6x6roHN77r
    AQwQCKtbgiXFvMY7xd/ZD8EcYs0hkjOsEXSgQaOVjxNc/k2MaATD1G3KdIBycRHU
    iYIEjdgtlk+b3RiO313qKoN1VtMjj3hE3uR/nQsFDqnKMTN3nXXGQkfX8XN2o4J5
    vKl39+ZIbOwBhltr3bOoHVYrxjjUxGhSPOBxriRC1W3ZmiPNLoRlsyb95PZT/0WA
    Zvv1bDaAAI5uuT45dSR7TZ6eAkjPsp0to3fk60TpCZOyVm2sACtmhjUqIOENSX/t
    YvP53FNOfaCDTvMPWeKUSb+2R6p9coTdUj+AhZBsOA==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDcJ2ErLUd5hlOQ
    hfwlGpEKAzFPCLn/4zLje9QPnOHy1g45KvLA8k0C6QH64xRUM/Ly/Nip/M00hdTh
    48m1tRVbDVNVSuCPM5VaAYcQacdXE1AfWNN/IXdSQ8rdH1aXYsU4TTwUFD/JcSNs
    C6hH3HBMs2t/n2uTHv8HFMkh0jyakneoyErxKYPmjikLGwpiDwZzU39MeGhbDpg+
    5E5kOAsrqgvBlCVrJkIhUxNMHjiPltgKk05RoM1OtCGxtSwmcO+4UqUCXTmz2P1F
    mYhDKFlRRrbry89Nm15Q5/TxOTEOZFAaPtv/V73my5KdRWj4Led8/RficWZotXwK
    4vRgJm2vAgMBAAECggEAXFhgV94cVwtTThIFnAKyyAJi0oYUjxNcKzOr1gi2dkf3
    m186iFiamRfn7rcFtfQ8elQ5BcS2xstEaqRD3eZhWNoUFHjeDPNUOHbfkrDsHshJ
    GX0G6hK9nFI3a91TUxjpJR6wjrOXtgWxGAcjxVDgAixYcSYL16Bu1SeQ3pDzPtpe
    EIAkGvOxwDSAnIPnQQuPk6wvGRSeKVh/jHoAIBi919zlEqsPAivYVzGrhRsQrRkE
    Qr25UNqqvdM0yKLvstEak5vYWQgwOZVekeN62Y1bAzlK44K3o1h49VaL/Wb1zlal
    0c0tAbCKpFLn1VMoCkGUujAhXkdwJMleT+QH8w2fUQKBgQDuxbCl4JOnVTNiHZp6
    /TWWoUl+h+1Nk3tvkg2UlII2pew8d5+PuB23dzRUuZMT69YtpcaaNEYdlAefnFlE
    iDEpNNmDIn8FjzGBa6fJjapo27YTqCEYry6dlShxzGhYtyWWIZICYEBD1PZmRpM1
    3fbEaVTX9E/qTlpsMpaZXt3ZEwKBgQDsCcsI4mW6aRqM9RisGtOCHgf3OFGZCdrb
    TEqMfvaIqEirLd4lC07Fh0ELgUEOGhkyLAMkzxLfVHquQ2cKE525sWX8fGyiuL65
    72sd7cGK6RyClrNYOhwanoLzP3WSUUfjceoU1ztFWlzMdIrs7dXsmdePra5Sn4KS
    5aFqyfPodQJ/RQTgCxLfm38FW1czUFnhI6l7lRe1gLcg9x9AzbIf8awEnXX2qZSP
    Anlypwr9eMSzJH7G6cwyeFpR2dFX/HdhvoeIWF+gV/sMVFzKI3jPyX+5IfV3m6sH
    zoVPK5Xqk7pdIwiRLB6mdPUaRHYiF3AR5LSN0d7NOu1rNdtprOu/NQKBgQCXxJg7
    By830/rRZYrOppUW1e5zRFAbId4KIZzRh5VHO0U2Y9CxavrkQVpOZnaI9bj7rJb8
    5PSSisQzJn2rWf+RdYJI/UvwuO9RqKLsZIKMqeS+Bt4cPYjyiLdUZppXUVHy6b0E
    V3vx1O9UOx9UxnxFnImhBaDP2WZgw6uteVsOPQKBgQCxwPERBrINASk2y+8C4an+
    faizEp3zmPriqWxQ/V412OSr50iBe6mjlS7H/SUF9HhAtN1Wi7k1V8RM532RfnM3
    O+e167a9wdqWUiPRcmUq8Q64kkJFC/y1XyaqTP7Gqb6sFOGJcSWrD4hTO9zo+sud
    1+H3gnrEv4kc0cizghteJw==
    -----END PRIVATE KEY-----
