apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mdm-system
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: backend
        app.kubernetes.io/version: "1.0.9"
        version: "1.0.9"
    spec:
      containers:
      - name: backend
        image: profavor2/mplatform-backend:1.0.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mdm-config
        - secretRef:
            name: mdm-secrets
        env:
        - name: JAVA_OPTS
          value: "-Xms4g -Xmx4g -XX:MaxMetaspaceSize=512m -XX:+UseSerialGC"
        - name: PORT
          value: "8080"
        - name: MAIL_CONFIG_PATH
          value: "/var/mail-config"
        volumeMounts:
        - name: mail-config
          mountPath: /var/mail-config
      volumes:
      - name: mail-config
        persistentVolumeClaim:
          claimName: mail-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mdm-system
spec:
  ports:
  - port: 8080
  selector:
    app: backend
