apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mdm-system
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: "1.5.47"
    version: "1.5.47"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/version: "1.5.47"
        version: "1.5.47"
    spec:
      hostAliases:
      - ip: "10.100.179.117"
        hostnames:
        - "mplatform.local"
      containers:
      - name: frontend
        image: profavor2/mplatform-frontend:1.5.47
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: mdm-config
        - secretRef:
            name: mdm-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mdm-system
spec:
  ports:
  - port: 3000
  selector:
    app: frontend
