// Mocks generated by Mockito 5.4.6 from annotations
// in mplatform_mobile/test/features/chat/presentation/providers/chat_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:mplatform_mobile/features/chat/data/repositories/chat_repository.dart'
    as _i4;
import 'package:mplatform_mobile/features/chat/data/services/chat_websocket_service.dart'
    as _i7;
import 'package:mplatform_mobile/features/chat/domain/models/chat_message_model.dart'
    as _i2;
import 'package:mplatform_mobile/features/chat/domain/models/chat_room_model.dart'
    as _i3;
import 'package:stomp_dart_client/stomp_dart_client.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatMessageModel_0 extends _i1.SmartFake
    implements _i2.ChatMessageModel {
  _FakeChatMessageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatRoomModel_1 extends _i1.SmartFake implements _i3.ChatRoomModel {
  _FakeChatRoomModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i4.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.ChatRoomModel>> getChatRooms() =>
      (super.noSuchMethod(
            Invocation.method(#getChatRooms, []),
            returnValue: _i5.Future<List<_i3.ChatRoomModel>>.value(
              <_i3.ChatRoomModel>[],
            ),
          )
          as _i5.Future<List<_i3.ChatRoomModel>>);

  @override
  _i5.Future<List<String>> getOnlineUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineUsers, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<dynamic>> getRoomMembers(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomMembers, [roomId]),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<_i2.ChatMessageModel>> getMessages(
    String? roomId, {
    int? page = 0,
    int? size = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [roomId],
              {#page: page, #size: size},
            ),
            returnValue: _i5.Future<List<_i2.ChatMessageModel>>.value(
              <_i2.ChatMessageModel>[],
            ),
          )
          as _i5.Future<List<_i2.ChatMessageModel>>);

  @override
  _i5.Future<_i2.ChatMessageModel> sendMessage(
    String? roomId, {
    required String? content,
    String? attachmentUrl,
    String? messageType = 'TEXT',
    String? fileUrl,
    String? fileName,
    int? fileSize,
    String? url,
    String? originalName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [roomId],
              {
                #content: content,
                #attachmentUrl: attachmentUrl,
                #messageType: messageType,
                #fileUrl: fileUrl,
                #fileName: fileName,
                #fileSize: fileSize,
                #url: url,
                #originalName: originalName,
              },
            ),
            returnValue: _i5.Future<_i2.ChatMessageModel>.value(
              _FakeChatMessageModel_0(
                this,
                Invocation.method(
                  #sendMessage,
                  [roomId],
                  {
                    #content: content,
                    #attachmentUrl: attachmentUrl,
                    #messageType: messageType,
                    #fileUrl: fileUrl,
                    #fileName: fileName,
                    #fileSize: fileSize,
                    #url: url,
                    #originalName: originalName,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ChatMessageModel>);

  @override
  _i5.Future<_i3.ChatRoomModel> createRoom({
    required String? title,
    required List<String>? participants,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRoom, [], {
              #title: title,
              #participants: participants,
            }),
            returnValue: _i5.Future<_i3.ChatRoomModel>.value(
              _FakeChatRoomModel_1(
                this,
                Invocation.method(#createRoom, [], {
                  #title: title,
                  #participants: participants,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ChatRoomModel>);

  @override
  _i5.Future<bool> markRoomAsRead(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#markRoomAsRead, [roomId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> fetchTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTotalUnreadCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<Map<String, dynamic>> uploadFile(
    List<int>? fileBytes,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [fileBytes, fileName]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<String> translateMessage(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#translateMessage, [text]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#translateMessage, [text]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> leaveRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveRoom, [roomId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoom, [roomId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> delegateCreator(String? roomId, String? newCreatorId) =>
      (super.noSuchMethod(
            Invocation.method(#delegateCreator, [roomId, newCreatorId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> inviteMembers(
    String? roomId,
    List<String>? userIds, {
    int? pastMessageHours = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #inviteMembers,
              [roomId, userIds],
              {#pastMessageHours: pastMessageHours},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> kickMember(String? roomId, String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#kickMember, [roomId, targetUserId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [ChatWebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatWebSocketService extends _i1.Mock
    implements _i7.ChatWebSocketService {
  MockChatWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.ChatMessageModel> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i5.Stream<_i2.ChatMessageModel>.empty(),
          )
          as _i5.Stream<_i2.ChatMessageModel>);

  @override
  _i5.Stream<String> get roomReadStream =>
      (super.noSuchMethod(
            Invocation.getter(#roomReadStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<Map<String, dynamic>> get presenceStream =>
      (super.noSuchMethod(
            Invocation.getter(#presenceStream),
            returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
          )
          as _i5.Stream<Map<String, dynamic>>);

  @override
  _i5.Stream<Map<String, dynamic>> get notificationStream =>
      (super.noSuchMethod(
            Invocation.getter(#notificationStream),
            returnValue: _i5.Stream<Map<String, dynamic>>.empty(),
          )
          as _i5.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i5.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onConnect(_i8.StompFrame? frame) => super.noSuchMethod(
    Invocation.method(#onConnect, [frame]),
    returnValueForMissingStub: null,
  );

  @override
  void subscribeToRoom(String? roomId) => super.noSuchMethod(
    Invocation.method(#subscribeToRoom, [roomId]),
    returnValueForMissingStub: null,
  );

  @override
  void unsubscribeFromRoom() => super.noSuchMethod(
    Invocation.method(#unsubscribeFromRoom, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
