// Mocks generated by Mockito 5.4.6 from annotations
// in mplatform_mobile/test/features/auth/presentation/screens/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:mplatform_mobile/core/auth/oidc_service.dart' as _i6;
import 'package:mplatform_mobile/features/auth/data/repositories/auth_repository.dart'
    as _i4;
import 'package:mplatform_mobile/features/auth/domain/models/auth_response.dart'
    as _i2;
import 'package:mplatform_mobile/features/auth/domain/models/user_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthResponse> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i3.UserModel> loginWithOidc({
    required String? authCode,
    required String? codeVerifier,
    String? tokenEndpoint =
        'http://localhost:8081/realms/mplatform/protocol/openid-connect/token',
    String? clientId = 'mdm-mobile',
    String? redirectUri = 'mplatform://oauth2redirect',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithOidc, [], {
              #authCode: authCode,
              #codeVerifier: codeVerifier,
              #tokenEndpoint: tokenEndpoint,
              #clientId: clientId,
              #redirectUri: redirectUri,
            }),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#loginWithOidc, [], {
                  #authCode: authCode,
                  #codeVerifier: codeVerifier,
                  #tokenEndpoint: tokenEndpoint,
                  #clientId: clientId,
                  #redirectUri: redirectUri,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i3.UserModel?>.value(),
          )
          as _i5.Future<_i3.UserModel?>);

  @override
  _i5.Future<List<_i3.UserModel>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i5.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i5.Future<List<_i3.UserModel>>);
}

/// A class which mocks [OidcService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOidcService extends _i1.Mock implements _i6.OidcService {
  MockOidcService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateCodeVerifier([int? length = 64]) =>
      (super.noSuchMethod(
            Invocation.method(#generateCodeVerifier, [length]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateCodeVerifier, [length]),
            ),
          )
          as String);

  @override
  String generateCodeChallenge(String? codeVerifier) =>
      (super.noSuchMethod(
            Invocation.method(#generateCodeChallenge, [codeVerifier]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generateCodeChallenge, [codeVerifier]),
            ),
          )
          as String);

  @override
  String buildAuthorizationUrl({
    required String? issuer,
    required String? clientId,
    required String? redirectUri,
    required String? codeChallenge,
    String? state,
    String? scope = 'openid profile email',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildAuthorizationUrl, [], {
              #issuer: issuer,
              #clientId: clientId,
              #redirectUri: redirectUri,
              #codeChallenge: codeChallenge,
              #state: state,
              #scope: scope,
            }),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#buildAuthorizationUrl, [], {
                #issuer: issuer,
                #clientId: clientId,
                #redirectUri: redirectUri,
                #codeChallenge: codeChallenge,
                #state: state,
                #scope: scope,
              }),
            ),
          )
          as String);

  @override
  _i5.Future<Map<String, dynamic>> exchangeCodeForTokens({
    required _i8.Dio? dio,
    required String? tokenEndpoint,
    required String? clientId,
    required String? redirectUri,
    required String? code,
    required String? codeVerifier,
    String? clientSecret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForTokens, [], {
              #dio: dio,
              #tokenEndpoint: tokenEndpoint,
              #clientId: clientId,
              #redirectUri: redirectUri,
              #code: code,
              #codeVerifier: codeVerifier,
              #clientSecret: clientSecret,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
