// Mocks generated by Mockito 5.4.6 from annotations
// in mplatform_mobile/test/features/inbox/presentation/screens/inbox_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mplatform_mobile/features/inbox/data/repositories/inbox_repository.dart'
    as _i3;
import 'package:mplatform_mobile/features/inbox/domain/models/inbox_folder_count_model.dart'
    as _i5;
import 'package:mplatform_mobile/features/inbox/domain/models/inbox_message_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInboxMessageModel_0 extends _i1.SmartFake
    implements _i2.InboxMessageModel {
  _FakeInboxMessageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InboxRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepository extends _i1.Mock implements _i3.InboxRepository {
  MockInboxRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.InboxMessageModel>> getMessages({
    String? folder = 'INBOX',
    int? page = 0,
    int? size = 20,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [], {
              #folder: folder,
              #page: page,
              #size: size,
              #keyword: keyword,
            }),
            returnValue: _i4.Future<List<_i2.InboxMessageModel>>.value(
              <_i2.InboxMessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.InboxMessageModel>>);

  @override
  _i4.Future<_i2.InboxMessageModel> getMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMessage, [id]),
            returnValue: _i4.Future<_i2.InboxMessageModel>.value(
              _FakeInboxMessageModel_0(
                this,
                Invocation.method(#getMessage, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.InboxMessageModel>);

  @override
  _i4.Future<_i2.InboxMessageModel> sendMessage(
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [request]),
            returnValue: _i4.Future<_i2.InboxMessageModel>.value(
              _FakeInboxMessageModel_0(
                this,
                Invocation.method(#sendMessage, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.InboxMessageModel>);

  @override
  _i4.Future<_i2.InboxMessageModel> saveDraft(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [request]),
            returnValue: _i4.Future<_i2.InboxMessageModel>.value(
              _FakeInboxMessageModel_0(
                this,
                Invocation.method(#saveDraft, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.InboxMessageModel>);

  @override
  _i4.Future<_i2.InboxMessageModel> updateDraft(
    String? id,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDraft, [id, request]),
            returnValue: _i4.Future<_i2.InboxMessageModel>.value(
              _FakeInboxMessageModel_0(
                this,
                Invocation.method(#updateDraft, [id, request]),
              ),
            ),
          )
          as _i4.Future<_i2.InboxMessageModel>);

  @override
  _i4.Future<_i2.InboxMessageModel> reply(
    String? id,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reply, [id, request]),
            returnValue: _i4.Future<_i2.InboxMessageModel>.value(
              _FakeInboxMessageModel_0(
                this,
                Invocation.method(#reply, [id, request]),
              ),
            ),
          )
          as _i4.Future<_i2.InboxMessageModel>);

  @override
  _i4.Future<_i2.InboxMessageModel> replyAll(
    String? id,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replyAll, [id, request]),
            returnValue: _i4.Future<_i2.InboxMessageModel>.value(
              _FakeInboxMessageModel_0(
                this,
                Invocation.method(#replyAll, [id, request]),
              ),
            ),
          )
          as _i4.Future<_i2.InboxMessageModel>);

  @override
  _i4.Future<_i2.InboxMessageModel> forward(
    String? id,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forward, [id, request]),
            returnValue: _i4.Future<_i2.InboxMessageModel>.value(
              _FakeInboxMessageModel_0(
                this,
                Invocation.method(#forward, [id, request]),
              ),
            ),
          )
          as _i4.Future<_i2.InboxMessageModel>);

  @override
  _i4.Future<void> toggleRead(String? id, bool? isRead) =>
      (super.noSuchMethod(
            Invocation.method(#toggleRead, [id, isRead]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleStar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleStar, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> moveToFolder(String? id, String? folder) =>
      (super.noSuchMethod(
            Invocation.method(#moveToFolder, [id, folder]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessage(String? id, {bool? permanent = false}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id], {#permanent: permanent}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> bulkAction(String? action, List<String>? messageIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkAction, [action, messageIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> recallMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#recallMessage, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i5.InboxFolderCountModel>> getFolderCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getFolderCounts, []),
            returnValue: _i4.Future<List<_i5.InboxFolderCountModel>>.value(
              <_i5.InboxFolderCountModel>[],
            ),
          )
          as _i4.Future<List<_i5.InboxFolderCountModel>>);

  @override
  _i4.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
